-- create database barm_user;
-- auto Generated on 2020-03-06
DROP TABLE IF EXISTS user_main;
CREATE TABLE user_main(
	id BIGINT (20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
	user_id BIGINT (20)  UNSIGNED UNIQUE NOT NULL DEFAULT 0 COMMENT '用户ID',
	username VARCHAR (64) NOT NULL DEFAULT '' COMMENT '用户名',
	`password` VARCHAR (64) NOT NULL DEFAULT '' COMMENT '密码',
	nickname VARCHAR (64) NOT NULL DEFAULT '' COMMENT '昵称',
	create_by VARCHAR (64) NOT NULL DEFAULT '' COMMENT '创建人',
	modify_by VARCHAR (64) NOT NULL DEFAULT '' COMMENT '修改人',
	gmt_create DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
	gmt_modify DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
	version BIGINT (20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '版本号',
	deleted TINYINT (1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '逻辑删 0 未删除 1 已删除',
	extend VARCHAR (256) NOT NULL DEFAULT '' COMMENT '冗余',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户主表';
